### ISSUE TITLE
Why is --mode manatory

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/TinyFPGA-Programmer-Application#11]
For instance, if I want to reset in an automated app I want to say:

qfprog --port /dev/ttyS3 --reset

There is no value to the --mode.

Sames issue if I just want to check crc

**Comment by coolbreeze413** [comment]
Yes, this is right, `mode` should be mandatory only while flashing. Will work on a fix for this.

**Comment by coolbreeze413** [comment]
Fixed with #12 .
